In [66]:
import pandas as pd

In [70]:
df = pd.read_csv('../data2/processed/merged_clean.csv', index_col = 0)

In [71]:
df

          id        vat       category   value  quantity
0        125  A28415495  Label Printer  239.00       1.0
1        139  B12026183    Accessories   43.80       1.0
2        149  B64898562    Accessories  103.38       3.0
3        168  A59555466    Accessories  753.49       1.0
4        235  A58244096      Printhead  899.91       3.0
...      ...        ...            ...     ...       ...
9765  119197  B66572249        Scanner   85.79       1.0
9768  119338  B34204974        Scanner  472.50       1.0
9769  119340  B70135371        Scanner  472.50       1.0
9770  119376  47364071X        Scanner  366.41       1.0
9771  119409  B80465172    Accessories  122.65       1.0

[9619 rows x 5 columns]

In [72]:
df['category'].value_counts()

Accessories                3268
Scanner                    2717
Label Printer              1028
Mobile Computing            766
Label                       555
Ribbon                      367
Card Ribbon                 222
Ticket Printer              219
Printhead                   199
Card                         89
Touch Screen & Computer      65
Card Printer                 63
RFID                         29
Tickets                      27
Wristband                     5
Name: category, dtype: int64

In [73]:
cat_list = list(df['category'].unique())
cat_list

['Label Printer',
 'Accessories',
 'Printhead',
 'Mobile Computing',
 'Scanner',
 'Label',
 'Ribbon',
 'Card Printer',
 'Card',
 'Card Ribbon',
 'Ticket Printer',
 'Tickets',
 'Touch Screen & Computer',
 'RFID',
 'Wristband']

In [74]:
for x in cat_list:
    df[x+'_value'] = df[df['category'] == x]['value']
    df[x+'_qty'] =  df[df['category'] == x]['quantity']

In [75]:
df

,id,vat,category,value,quantity,Label Printer_value,Label Printer_qty,Accessories_value,Accessories_qty,Printhead_value,...,Ticket Printer_value,Ticket Printer_qty,Tickets_value,Tickets_qty,Touch Screen & Computer_value,Touch Screen & Computer_qty,RFID_value,RFID_qty,Wristband_value,Wristband_qty
0,125,A28415495,Label Printer,239.00,1.0,239.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,139,B12026183,Accessories,43.80,1.0,NaN,NaN,43.80,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,149,B64898562,Accessories,103.38,3.0,NaN,NaN,103.38,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,168,A59555466,Accessories,753.49,1.0,NaN,NaN,753.49,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,235,A58244096,Printhead,899.91,3.0,NaN,NaN,NaN,NaN,899.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9765,119197,B66572249,Scanner,85.79,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9768,119338,B34204974,Scanner,472.50,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9769,119340,B70135371,Scanner,472.50,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9770,119376,47364071X,Scanner,366.41,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9771,119409,B80465172,Accessories,122.65,1.0,NaN,NaN,122.65,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df['vat'].value_counts()

B85538601    25
A31008766    12
A28021715    12
A78374725    11
A78032315    10
             ..
B60735768     1
B86710860     1
B61904249     1
Q9155027G     1
21012595W     1
Name: vat, Length: 7625, dtype: int64

In [77]:
df = df.drop_duplicates('vat')

In [78]:
df['vat'].value_counts()

A11606134    1
F37015856    1
B46738324    1
31866425V    1
B86585015    1
            ..
A25354234    1
B73637084    1
B81612020    1
E06611511    1
21012595W    1
Name: vat, Length: 7625, dtype: int64

In [79]:
df = df.fillna(0)

In [82]:
df.shape

(7625, 35)

Merge with the Companies enrich Dataframe

In [83]:
companies = pd.read_csv('../data2/processed/final_companies.csv', index_col = 0)

In [84]:
companies

,vat,CNAE,provincia,provincia_encoded,cnae_encoded
0,A28415495,3212 - FabricaciÃ³n de artÃ­culos de joyerÃ­a y ...,Madrid,30,199
1,B12026183,4631 - Comercio al por mayor de frutas y hort...,CastellÃ³n,11,263
2,B64898562,6201 - Actividades de programaciÃ³n informÃ¡tica,Barcelona,7,375
3,A59555466,7112 - Servicios tÃ©cnicos de ingenierÃ­a y otr...,Barcelona,7,403
4,A58244096,"2030 - FabricaciÃ³n de pinturas, barnices y re...",Barcelona,7,101
...,...,...,...,...,...
8330,Y3993172H,NaN,NaN,53,497
8331,E40566135,NaN,NaN,53,497
8332,32791005C,NaN,NaN,53,497
8333,50763821S,NaN,NaN,53,497
8334,51070159Q,NaN,NaN,53,497

In [87]:
dff = pd.merge(df, companies, how='left',on = 'vat')

In [88]:
dff

,id,vat,category,value,quantity,Label Printer_value,Label Printer_qty,Accessories_value,Accessories_qty,Printhead_value,...,Touch Screen & Computer_value,Touch Screen & Computer_qty,RFID_value,RFID_qty,Wristband_value,Wristband_qty,CNAE,provincia,provincia_encoded,cnae_encoded
0,125,A28415495,Label Printer,239.00,1.0,239.0,1.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,3212 - FabricaciÃ³n de artÃ­culos de joyerÃ­a y ...,Madrid,30,199
1,139,B12026183,Accessories,43.80,1.0,0.0,0.0,43.80,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4631 - Comercio al por mayor de frutas y hort...,CastellÃ³n,11,263
2,149,B64898562,Accessories,103.38,3.0,0.0,0.0,103.38,3.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,6201 - Actividades de programaciÃ³n informÃ¡tica,Barcelona,7,375
3,168,A59555466,Accessories,753.49,1.0,0.0,0.0,753.49,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,7112 - Servicios tÃ©cnicos de ingenierÃ­a y otr...,Barcelona,7,403
4,235,A58244096,Printhead,899.91,3.0,0.0,0.0,0.00,0.0,899.91,...,0.0,0.0,0.0,0.0,0.0,0.0,"2030 - FabricaciÃ³n de pinturas, barnices y re...",Barcelona,7,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8330,119197,B66572249,Scanner,85.79,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,6202 - Actividades de consultorÃ­a informÃ¡tica,Barcelona,7,376
8331,119338,B34204974,Scanner,472.50,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,"4741 - Comercio al por menor de ordenadores, ...",Palencia,36,307
8332,119340,B70135371,Scanner,472.50,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4941 - Transporte de mercancÃ­as por carretera,La CoruÃ±a,25,336
8333,119376,47364071X,Scanner,366.41,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,7420 - Actividades de fotografÃ­a,La CoruÃ±a,25,411
8334,119409,B80465172,Accessories,122.65,1.0,0.0,0.0,122.65,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4663 - Comercio al por mayor de maquinaria pa...,Madrid,30,285

In [93]:
dff = dff.drop_duplicates()

In [94]:
dff

,id,vat,category,value,quantity,Label Printer_value,Label Printer_qty,Accessories_value,Accessories_qty,Printhead_value,...,Touch Screen & Computer_value,Touch Screen & Computer_qty,RFID_value,RFID_qty,Wristband_value,Wristband_qty,CNAE,provincia,provincia_encoded,cnae_encoded
0,125,A28415495,Label Printer,239.00,1.0,239.0,1.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,3212 - FabricaciÃ³n de artÃ­culos de joyerÃ­a y ...,Madrid,30,199
1,139,B12026183,Accessories,43.80,1.0,0.0,0.0,43.80,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4631 - Comercio al por mayor de frutas y hort...,CastellÃ³n,11,263
2,149,B64898562,Accessories,103.38,3.0,0.0,0.0,103.38,3.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,6201 - Actividades de programaciÃ³n informÃ¡tica,Barcelona,7,375
3,168,A59555466,Accessories,753.49,1.0,0.0,0.0,753.49,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,7112 - Servicios tÃ©cnicos de ingenierÃ­a y otr...,Barcelona,7,403
4,235,A58244096,Printhead,899.91,3.0,0.0,0.0,0.00,0.0,899.91,...,0.0,0.0,0.0,0.0,0.0,0.0,"2030 - FabricaciÃ³n de pinturas, barnices y re...",Barcelona,7,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8330,119197,B66572249,Scanner,85.79,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,6202 - Actividades de consultorÃ­a informÃ¡tica,Barcelona,7,376
8331,119338,B34204974,Scanner,472.50,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,"4741 - Comercio al por menor de ordenadores, ...",Palencia,36,307
8332,119340,B70135371,Scanner,472.50,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4941 - Transporte de mercancÃ­as por carretera,La CoruÃ±a,25,336
8333,119376,47364071X,Scanner,366.41,1.0,0.0,0.0,0.00,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,7420 - Actividades de fotografÃ­a,La CoruÃ±a,25,411
8334,119409,B80465172,Accessories,122.65,1.0,0.0,0.0,122.65,1.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,4663 - Comercio al por mayor de maquinaria pa...,Madrid,30,285

In [95]:
dff.to_csv('../data2/processed/18.04.2020_Dataframe_for_clustering')